const nodemailer = require("nodemailer");
const logger = require('../config/logger');

const Rabbitmq_sendMail = (sendtoID) => {

    // 1 - transporter use to transfport to email
    const transport =  nodemailer.createTransport({
        service :"gmail",
        auth: {
            user : process.env.FROM_ID,
            pass : process.env.PASSWORD
        }
    })

    //2 transport object
    const formatedMail = {
        form :process.env.FROM_ID,
        to: sendtoID,
        subject : "HELLO USER",
        html :`<h1><b>Greetings!!<b> <br>This is Autogenerated main From EmployeePayroll App you are Regsitered</h1>`
    }

    //3.send mail with defined transport object
    return new Promise((resolve,reject) => {

        transport.sendMail(formatedMail,(err,info)=> {
            if(err){
             logger.log('error',err)   //for export.module
            //  logger.logger.log('error',err) //for exports.logger
               return reject;
            }
            else{
                
                logger.log('info', info );   
                // logger.logger.log('info', info );
              return resolve("you have got mail");
            }
        })

    }) 
}

module.exports = Rabbitmq_sendMail ;



